services:
  postgres:
    image: postgres:15
    container_name: starsoft-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starsoft
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: starsoft-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

  app:
    build: .
    container_name: starsoft-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data: